name: PR Verification
# This workflow is triggered on open PRs
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Verify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cfn-lint

      - name: Lint Cloudformation Template
        run: |
          cfn-lint deploy/cloudformation.template.yml

      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: us-east-2

      # - name: Validate Cloudformation Template
      #   run: |
      #     aws cloudformation validate-template --template-body file://deploy/cloudformation.template.yml